type: rpm-ostree
repos:
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  - https://repository.mullvad.net/rpm/stable/mullvad.repo
  - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
optfix:
  - Mullvad VPN
install:
# display manager
  - sddm
  - sddm-themes

# GUI
  - nwg-shell
  - aylurs-gtk-shell
  - swww
  - waypaper


# Theme
  - adwaita-qt5
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme 
  - papirus-icon-theme

# launcher
  - fuzzel

# environment
  - xorg-x11-server-Xwayland
  - polkit
  - lxpolkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - gnome-keyring
  - pavucontrol
  - playerctl
  - qt5-qtwayland
  - qt6-qtwayland
  - vulkan-validation-layers
  - vulkan-tools
  - google-noto-emoji-fonts
  - gnome-disk-utility
  - fcitx5
  
# sound
  - wireplumber
  - pipewire
  - pamixer
  - mpd
  - ncmpcpp
  - sox

# networking
  - network-manager-applet
  - NetworkManager-openvpn
  - NetworkManager-openconnect
  - bluez
  - bluez-tools
  - blueman

# file manager
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver
  - imv
  - p7zip
  - unrar-free
  - gvfs-smb
  - dolphin

# screenshot/recording
  - slurp
  - grim
  - wf-recorder

# display
  - wlr-randr
  - wlsunset
  - grimshot
  - light
  - swaylock
  - swayidle
  - kanshi

# terminal
  - kitty
  - foot
  - xfce4-terminal

# mpv, since flatpak mpv and celluloid have issues
  - mpv

# utilities
  - tailscale
  - mullvad-vpn
  - tmux
  - screen
  - pass
  - pass-otp

# virtualization
  - qemu-kvm
  - libvirt-daemon
  - libvirt-daemon-config-network
  - libvirt-daemon-driver-interface
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nwfilter
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-kvm
  - libvirt-client
  - virt-install
  - virt-manager
