type: rpm-ostree
repos:
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  - https://copr.fedorainfracloud.org/coprs/tofik/sway/repo/fedora-39/tofik-sway-fedora-39.repo
  - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-39/tofik-nwg-shell-fedora-39.repo
install:
# display manager
  - sddm
  - sddm-themes

# theme and GUI
  - nwg-shell
  - adwaita-qt5
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme 
  - papirus-icon-theme

# launcher
  - fuzzel

# environment
  - xorg-x11-server-Xwayland
  - polkit
  - lxpolkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - gnome-keyring
  - pavucontrol
  - playerctl
  - qt5-qtwayland
  - qt6-qtwayland
  - vulkan-validation-layers
  - google-noto-emoji-fonts

# sound
  - wireplumber
  - pipewire
  - mpd
  - ncmpcpp
  - sox

# networking
  - network-manager-applet
  - bluez
  - bluez-tools
  - blueman

# file manager
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver

# screenshot
  - slurp
  - grim

# display
  - wlr-randr
  - wlsunset
  - grimshot
  - light
  - swaylock
  - swayidle
  - kanshi

# terminal
  - kitty
  - foot

# notifications
  - swaync

# mpv, since flatpak mpv and celluloid have issues
  - mpv

# utilities
  - tailscale
  - tmux
  - screen
  - pass
  - pass-otp

# virtualization
  - qemu-kvm
  - libvirt-daemon
  - libvirt-daemon-config-network
  - libvirt-daemon-driver-interface
  - libvirt-daemon-driver-network
  - libvirt-daemon-driver-nwfilter
  - libvirt-daemon-driver-qemu
  - libvirt-daemon-driver-secret
  - libvirt-daemon-driver-storage-core
  - libvirt-daemon-driver-storage-disk
  - libvirt-daemon-driver-storage-scsi
  - libvirt-daemon-kvm
  - libvirt-client
  - virt-install
  - virt-manager
