type: fonts
fonts:
  nerd-fonts:
    - Iosevka
    - FiraCode
    - Hack
    - SourceCodePro
    - Terminus
    - JetBrainsMono
    - NerdFontsSymbolsOnly
  google-fonts:
    - Roboto
    - Open Sans
    - Source Serif 4
    - Source Sans 3
    - IBM Plex Sans
    - IBM Plex Serif
    - EB Garamond
