# image will be published to ghcr.io/<user>/<name>
name: sway-nvidia
# description will be included in the image's metadata
description: sway-nvidia image based on sericiea

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-files.yml
  - from-file: common-akmods.yml
  - from-file: common-packages.yml
  - from-file: common-fonts.yml
  - from-file: common-scripts.yml
  - from-file: common-flatpaks.yml
  - type: signing
  - from-file: common-systemd.yml
  - from-file: sway-packages.yml
